### ISSUE TITLE
How do I use X-SMTPAPI with mail helper?

### ISSUE THREAD

**Issue by omjokine** [sendgrid/smtpapi-nodejs#20]
Is it possible to use this library with helper class (const helper = require('sendgrid').mail) ?

I tried many ways but no lucky. For example:
mail.addHeader(new helper.Header('X-SMTPAPI', '{"to": ["to_address@example.com"]}'));

and:
    const smtpapi = require('smtpapi');
    var header = new smtpapi();
    header.addTo('to_address@example.com');
    var headers = { 'X-SMTPAPI': header.jsonString() };
    var request = sg.emptyRequest({
      method: 'POST',
      path: '/v3/mail/send',
      body: mail.toJSON(),
      headers,
    });

**Comment by thinkingserious** [comment]
Hello @omjokine,

The functionality of the X-SMTPAPI helper is now included in the v3 mail/send endpoint.

Please check out the comparison here: https://sendgrid.com/docs/Classroom/Send/v3_Mail_Send/how_to_migrate_from_v2_to_v3_mail_send.html

Thanks!
