### ISSUE TITLE
Setting a batch id results in emails not being sent

### ISSUE THREAD

**Issue by alsoicode** [sendgrid/smtpapi-nodejs#21]
Hello. I'm leveraging the smtpapi, and when I set a batch id via:

    smtpHeader.setBatchId(campaign._id); // e.g.: "b57a2545-6cb4-4f37-a840-b8095390f223"

along with `setSendAt()`, I never receive the email. If I remove the batch id, I do.

are there limits on how many characters I can set the batch  id to?

**Comment by thinkingserious** [comment]
Hi @alsoicode,

How did you [create the batch id](https://sendgrid.com/docs/API_Reference/SMTP_API/scheduling_parameters.html)?

With Best Regards,

Elmer

**Comment by alsoicode** [comment]
In my case, I'm creating the smtp header and message in a child process, then sending the message.

Example. `campaign` is a Mongoose object instance. I'd like to be able to use my database object's id so I have an easy way of issuing a cancel if needs be.

```
const smtpHeader = new smtpApi();
smtpHeader.setSendAt(campaign.publishAtEpoch);
smtpHeader.setBatchId(campaign._id);
```

**Comment by thinkingserious** [comment]
Are you using [this endpoint](https://sendgrid.com/docs/API_Reference/Web_API_v3/cancel_schedule_send.html) to generate it?

**Comment by alsoicode** [comment]
Apparently I missed the part in the docs about generating a valid batch id :)

I will look into that, and close this request. Thanks!

**Comment by thinkingserious** [comment]
Awesome! If you still have any issues feel free to reopen.
