### ISSUE TITLE
Add a Code Of Conduct

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/smtpapi-nodejs#23]
Add a file to the root of this repo called CODE_OF_CONDUCT.md, with the content from the [same file in our docs repo](https://github.com/sendgrid/docs/pull/3048).

**Comment by Jdtanacredi** [comment]
I'll do this real quick for ya

**Comment by PREMPRAKASHSINGH** [comment]
@thinkingserious  Is it still open?

**Comment by thinkingserious** [comment]
@PREMPRAKASHSINGH,

No, but thanks for checking :)
