### ISSUE TITLE
npm test is failing on older NodeJs versions due to `const` declaration

### ISSUE THREAD

**Issue by mbernier** [sendgrid/smtpapi-nodejs#36]
It seems like the older versions of node doesn't know what to do with `const` variables during testing in travis. 

[Travis reporting failures](https://travis-ci.org/sendgrid/smtpapi-nodejs/builds/291085862?utm_source=github_status&utm_medium=notification)

**Comment by mgingras** [comment]
@mbernier Looks like mocha drops support for 10.x as of their 4.0 release https://github.com/mochajs/mocha/releases . Freezing dev dependencies should keep tests passing. (Creating pr)

**Comment by gr8shivam** [comment]
As the project dependencies have dropped support for older versions of Node, tests for these versions will always fail.

Created PR #37 to remove older versions of node and add newer versions of node in travis config.
