### ISSUE TITLE
Add esdoc support

### ISSUE THREAD

**Issue by mbernier** [sendgrid/smtpapi-nodejs#50]
#### Issue Summary

Creating local documentation can be super helpful

1. Force a version of chai and install esdoc and coverage plugin
```
npm i chai@2.3.0 esdoc esdoc-coverage-plugin
```

2. In the root dir, create .esdoc.json with the following:
```
{
    "source": "./lib",
    "destination": "./docs",
    "plugins": [
      {
        "name": "esdoc-coverage-plugin", 
        "option": {
          "enable": true,
          "kind": ["class", "method", "member", "get", "set", "constructor", "function", "variable"]
        }
      }
    ]
  }
```

3. Update .gitignore by adding `docs` to the list of files to ignore
4. Look at [this PR](https://github.com/sendgrid/sendgrid-nodejs/pull/549/files) and make the same changes to the files here in smtpapi-nodejs as were made to CONTRIBUTING and USAGE in sendgrid-nodejs

**Comment by mptap** [comment]
@mbernier: I'm taking this.
