### ISSUE TITLE
Space added in substitution value 

### ISSUE THREAD

**Issue by dennyriadi** [sendgrid/smtpapi-nodejs#77]
#### Issue 

So I am following the example code in the repo and attempt to send email to multiple recipients using multiple substitution values like so:

```javascript 
header.setTos(['you@youremail.com', 'other@otheremail.com', ....);
header.addSubstitution('{{token}}', ['...', '...', '1fccc78932657d7d024521eee12a90', '...']);
```
The emails are being delivered successfully but the tokens are sometimes set randomly with space around it (e.g. "1fccc78932657d7d024521 eee12a90")

Checked the actual payload being sent to the server and I can verify that the token values do not contain spaces.

#### Technical details:

* smtpapi-nodejs Version: 1.3.1
* Node.js Version: 6.x.x

**Comment by dennyriadi** [comment]
Maybe related to this https://github.com/sendgrid/sendgrid-php/issues/37 ?

**Comment by thinkingserious** [comment]
Hi @dennyriadi,

I don't think issue #37 is related. 

I believe this issue is best supported by our [support team](https://support.sendgrid.com) as I don't believe this is a SDK/library level issue.

Thanks!

With Best Regards,

Elmer

**Comment by eshanholtz** [comment]
Closing as this was marked as a non-library issue.
